version: '3.0'
services:
  sentiment-analysis:
    image: "peaasjay/sentiment-frontend"
    ports:
      - "80:80"
    links:
      - "sentiment-webapp:sentiment-webapp"
      - "sentiment-logic:sentiment-logic"
    restart: always
  sentiment-webapp:
    image: "peaasjay/sentiment-webapp" 
    ports:
      - "8080:8080"
    restart: always
  sentiment-logic:
    image: "peaasjay/sentiment-logic"
    ports:
      - "5050:5000"
    restart: always
